### ISSUE TITLE
chinese() does not return GMP

### ISSUE THREAD

**Issue by hvds** [danaj/Math-Prime-Util-GMP#28]
Under profiling I noticed `MPU::chinese()` was doing a lot of work then always calling `MPUG::chinese`, so I changed my code to call the latter directly only to find my code stopped working. It turned out that while MPU is giving me a `Math::GMP` object back, MPUG-0.52 is giving me a PV/NV dualvar.

```
% perl -MMath::GMP -MMath::Prime::Util::GMP=chinese -E '
  # generate 210^10-1
  $z=chinese(map [$_-1,$_], map Math::GMP->new($_)**10, qw{2 3 5 7});
  say $z; say $z % 2; say ref($z)
'
166798809782009999999999
0

% 
```

I assume this is a bug - it would seem perverse if not, and would certainly be worth a mention in the docs.

I see the most recent commit is also fixing bugs in `chinese()`, so perhaps this is already fixed in github.

**Comment by trizen** [comment]
`Math::Prime::Util::GMP` always returns strings. This is documented in the description section:
![mpu-gmp](https://user-images.githubusercontent.com/614513/152001568-567f34d5-0aa6-4e36-bdf5-4b9ae67c5a25.png)

**Comment by hvds** [comment]
Oh I missed that - I looked briefly at the top of the docs, but primarily at the docs for `chinese` itself. I think I may have made this mistake before, and will probably make it again in a year or two - it seems such unobvious behaviour to me. I'd love to have an interface that avoided all the unnecessary round-tripping, but I'll close the ticket.

In any case my code is still a chunk faster calling this even with manual upgrade of the return value:
```
before:
 my $m = chinese(map [ -$_, $q[$_] ], 0 .. $#q);
 # spent   121s making  3821981 calls to Math::Prime::Util::chinese, avg 32µs/call
 # spent  60.4s making  3821981 calls to Math::Prime::Util::GMP::chinese, avg 16µs/call
 # spent  25.8s making 22931886 calls to Math::GMP::__ANON__[Math/GMP.pm:36], avg 1µs/call
 # spent  21.4s making  3821981 calls to Math::Prime::Util::_to_gmp, avg 6µs/call
 # spent  12.4s making  3733976 calls to Math::GMP::__ANON__[Math/GMP.pm:37], avg 3µs/call
after:
 my $m = Math::GMP->new(chinese(map [ -$_, $q[$_] ], 0 .. $#q));
 # spent  66.2s making  3821981 calls to Math::Prime::Util::GMP::chinese, avg 17µs/call
 # spent  22.8s making 19109905 calls to Math::GMP::__ANON__[Math/GMP.pm:36], avg 1µs/call
 # spent  20.8s making  3821981 calls to Math::GMP::new, avg 5µs/call
```
I _think_ the normally excellent NYTProf is double-counting some of this - that the 121s attributed to `MPU::chinese` also includes the 60s attributed to `MPUG::chinese`, for example - but the speedup is real and significant.
