### ISSUE TITLE
is quadratic residue?

### ISSUE THREAD

**Issue by hvds** [danaj/Math-Prime-Util-GMP#32]
I think it would be a good idea for the docs for `kronecker` to stress that when `n` is _not_ a prime that this will _not_ tell you whether there exists some x such that x^2 == a (mod n): it is easy to assume that the Kronecker symbol extends things in a way that preserves that property.

It would also be really useful to have a function that _does_ answer that question, or a cross-reference to `sqrtmod` if we can do no better than call that.

**Comment by danaj** [comment]
Noted in documentation and adding a function `is_qr(a,n)` that returns a boolean for all positive inputs.  It requires factoring n, and is somewhat faster than sqrtmod but not a huge amount more.

**Comment by danaj** [comment]
The version being checked in just does the sqrtmod internally.  I'll look into performance later (the XS and PP versions under progress are faster).
