### ISSUE TITLE
t/17-pseudoprime.t currently (commit 66599af7) failing test 971

### ISSUE THREAD

**Issue by sisyphus** [danaj/Math-Prime-Util-GMP#41]
Version 0.52 tests cleanly.
<code>
.....
ok 970 - Lucas sequence 8 1 -1 47
not ok 971 - Lucas sequence 124838608575421729 82826032115733949 1 9
\#   Failed test 'Lucas sequence 124838608575421729 82826032115733949 1 9'
\#   at t/17-pseudoprime.t line 301.
\#     Structures begin differing at:
\#          $got->[0] = '4435142355437030'
\#     $expected->[0] = '105023007914661659'
ok 972 - Lucas sequence 124838608575421729 82826032115733949 1 9
.....
</code>

This is on Windows, perl-5.36.0, for both <code>nvtype='double'</code> and <code>nvtype='__float128'</code> builds.
(I haven't tested on <code>nvtype='long double'</code> builds.)

I haven't investigated this issue at all - my immediate impression is that it's probably a bug in the test script.
Let me know if you'd like me to take a closer look.

Cheers,
Rob

**Comment by danaj** [comment]
I'm not seeing it here but not a Windows machine.  I'll look into it -- many thanks for reporting.

I recently changed the Lucas sequence code to accept bigint P and Q for all routines.  That isn't normally used for things like primality testing, but (1) it was inconsistent, and (2) there are some applications that want large P/Q.

**Comment by danaj** [comment]
I think I understand what's happening.  I left the old lucas_sequence() routine alone, allowing large values for the new functions (lucasu, lucasv, lucasuv, lucasumod, lucasvmod, lucasuvmod).

The new test value is meant to test for an internal overflow that was happening, but is only appropriate for 64-bit IV.  On 32-bit IV it will overflow the input values.

**Comment by sisyphus** [comment]
The above failure was for 64-bit perl's whose IV is 64-bit (<code>ivsize=8</code>).
For my 32-bit build of perl-5.36.0, with 32-bit IV (<code>ivsize=4</code>), I get 2 failures:
<code>
....
ok 992 - Lucas sequence 1001 -4 4 50
not ok 993 - Lucas sequence 124838608575421729 82826032115733949 1 9
\#   Failed test 'Lucas sequence 124838608575421729 82826032115733949 1 9'
\#   at t/17-pseudoprime.t line 301.
\#     Structures begin differing at:
\#          $got->[0] = '0'
\#     $expected->[0] = '1.05023007914662e+17'
not ok 994 - Lucas sequence 124838608575421729 82826032115733949 1 9
\#   Failed test 'Lucas sequence 124838608575421729 82826032115733949 1 9'
\#   at t/17-pseudoprime.t line 302.
\#     Structures begin differing at:
\#          $got->[0] = '105023007914661659'
\#     $expected->[0] = '1.05023007914662e+17'
ok 995 - Lucas sequence 1001 -4 7 50
....
</code>>
In case it's relevant, my version of Math::BigInt is 1.999830, which is what shipped with perl-5.36.0 source.

With my 32-bit build of perl-5.36.0, built with a 64-bit IV(<code>ivsize=8</code>), the failure is the same as reported in my original post - which is probably not surprising.

Cheers,
Rob

**Comment by sisyphus** [comment]
Commit  7371d2a fixes the failures on the 32-bit Windows builds, but not the 64-bit builds.
The thing about 64-bit Windows is that, unlike 64-bit *nix systems, the Windows <code>long int</code> is still only 4 bytes.
On such Windows systems, the 64-bit IV (<code>long long int</code>) overflows the <code>long int</code>.

And the <code>mpz\_\*\_ui</code> and <code>mpz\_\*\_si</code> functions will only look at the 4 least significant bytes of the IVs that they receive.
On Windows we therefore find that if perl's IV is 64-bits then:
```
> perl -MMath::GMPz=":mpz" -le "$Z = Math::GMPz->new();$max = ~0; Rmpz_set_ui($Z, $max); print $max; print $Z;"  
18446744073709551615
4294967295
```
And that is expected behaviour.
I wonder if this is what's tripping up this particular failing test. It wouldn't be the first time.
(It could be something else entirely, of course ;-)

Cheers,
Rob

**Comment by danaj** [comment]
Yes, that would cause problems as we think we have 64-bit support (Perl is 64-bit) so we run the large test.  Then this function is going to get called, doing the naive set:

```
void lucas_seq(mpz_t U, mpz_t V, mpz_t n, IV P, IV Q, mpz_t k, mpz_t Qk, mpz_t t)
{
  mpz_t mP, mQ;
  mpz_init_set_si(mP, P);
  mpz_init_set_si(mQ, Q);
  lucasuvmod(U, V, mP, mQ, k, n, t);
  mpz_powm(Qk, mQ, k, n);
  mpz_clear(mQ); mpz_clear(mP);
}
```

Something similar caused a test failure a few years ago.  I should spend some time going through the code to check for other cases.  I've tried to handle it in some recent changes, but those are all internal.

From the docs:

>   "P and Q are restricted to native signed integers." 

which leaves things a bit murky.

**Comment by sisyphus** [comment]
The perls that pose the problem will be those where $Config{ivsize} is 8 && $Config{longsize} is 4.
In XS you can detect such a perl (even at the preprocessing stage) by checking the values of IVSIZE and LONGSIZE.

IIRC, Math::GMP's new() function handles the issue by essentially replacing both <code>mpz_set_ui(A, SvUV(b))</code> and <code>mpz_set_si(A, SvIV(b))</code> calls with <code>mpz_set_str(A, SvPV_nolen(b), 10)</code> - irrespective of the relationship between LONGSIZE and IVSIZE. It seems to work well enough.

In my own Math::GMPz, I ended up writing an <code>Rmpz_set_uj</code> and <code>Rmpz_set_sj</code> function, along with an <code>Rmpz_set_IV</code> function that calls either the <code>Rmpz_set_uj</code> or the <code>Rmpz_set_sj</code> function, as appropriate.
(<code>Rmpz_set_IV</code> is available to all perls, but <code>Rmpz_set_uj</code> and <code>Rmpz_set_sj</code> are implemented only if <code>IVSIZE > LONGSIZE</code>.)

Anyway, @danaj,  you'll work out what's best for you, as time permits ;-)

It's a pity that gmp doesn't offer the '_uj' and '_sj' variants, like the mpfr library does.

Cheers,
Rob

**Comment by danaj** [comment]
:)  I just finished adding mpz_set_uv, mpz_set_iv, and mpz_get_uv functions on my machine, will continue tomorrow.  All of my usages of the mp?_*{u,s}i* functions should also be looked at (e.g. mpz_cmp_ui).

I'll take a look.  I was trying to avoid using the Perl defines for the type sizes, but that means I can't easily define the extra call away on most platforms.  I don't think it's a big performance issue.  It sounds like we have something fairly similar, I just built in the uj/sj functions into the uv/iv function directly.

**Comment by sisyphus** [comment]
I've taken a rather lazy approach to my <code>Rmpz_cmp_IV</code>, by making use of mpz_set_str().
I might see if I can improve on that.

Ping me when you've finished updating the M::P::U::G github repo and I'll run a check.
Of course, you can also run the check if you have a 32-bit *nix build of -Duse64bitint perl.

Cheers,
Rob

**Comment by danaj** [comment]
I used to use the GCC compiler farm to check different platforms, but my SSH key stopped working a while back.  All my home machines are boxed up so I don't have a lot of testing platforms any more.

**Comment by sisyphus** [comment]
Current github version (commit a3f9cfd) is building and testing fine for me for both ivsize=64 and ivsize=32.

When ivsize is 32, I see this warning in relation to the compilation of utility.c:
```
utility.c: In function 'mpz_set_uv':
utility.c:156:22: warning: right shift count >= width of type [-Wshift-count-overflow]
  156 |     mpz_set_ui(n, (v >> 32));
```
But the tests all pass, anyway.

Cheers,
Rob

**Comment by danaj** [comment]
I think this is done, I believe that warning should be gone.  I'm working on trial division revamp which is taking longer than I thought.

**Comment by sisyphus** [comment]
> I believe that warning should be gone. 

Yes, all looks good.
Closing, on the basis that this has now been fixed in github.
@danaj, of course, please feel free to re-open if you'd prefer.
(I'm never sure whether issues should be kept open until a fixed version is released on CPAN.)

Cheers,
Rob
