### ISSUE TITLE
chinese([a, 0], ...) fails with a floating-point exception

### ISSUE THREAD

**Issue by trizen** [danaj/Math-Prime-Util-GMP#7]
When `n` is 0 in the first array `[a,n]` provided to the `chinese()` function, it fails with a floating-point exception error.

Here is the Perl code which reproduces the issue:
```perl
use 5.010;
use strict;
use warnings;

use Math::Prime::Util::GMP qw(chinese);
say chinese([3,5],[2,0]);           # this returns undef
say chinese([3,0],[2,3]);           # this fails with a floating point exception
```

Output:
```

[1]    4489 floating point exception (core dumped)  perl x.pl
```
(tested against the latest commit, but also reproducible with v0.41 from CPAN)

**Comment by danaj** [comment]
Great find.  This also fails in a more annoying (internally) way:

    say chinese([3,5],[3,0],[2,3])

GMP really doesn't like B = A mod 0.
